### ISSUE TITLE
`views per month` or `views/month` solo badge

### ISSUE THREAD

**Issue by mdsrqbl** [u8views/go-u8views#33]
Hi,
This is a great service and I have been using it for my repo for a while now. 

I wanted to display a single badge for `views per month` or `views/month` instead of 4 different badges in a single svg. I am guessing this would be a very straightforward endpoint to implement since all the functionality already exists in other places.

Thanks

**Comment by YaroslavPodorvanov** [comment]
```text
[![u8views profile views](https://u8views.com/api/v1/github/profiles/121827373/views/month-count.svg)](https://u8views.com/github/u8views)
[![u8views profile views](https://u8views.com/api/v1/github/profiles/121827373/views/week-count.svg)](https://u8views.com/github/u8views)
[![u8views profile views](https://u8views.com/api/v1/github/profiles/121827373/views/day-count.svg)](https://u8views.com/github/u8views)
```
