### ISSUE TITLE
Profile views counter increases when owner account opens profile page

### ISSUE THREAD

**Issue by helitopia** [u8views/go-u8views#34]
Hi,
Thank you for creating such a great service

Just wanted to inquire whether it is expected behavior that when I open my profile page, then refresh it - the profile view counter increases by 1 every time

It is just unfortunate that such behavior may render the statistic imprecise as I am not sure that views of your own profile should be considered.

Opened profile page:
![image](https://github.com/u8views/go-u8views/assets/92454023/1281206a-def9-490a-848f-28045a3a1753)

Refreshed the page:
![image](https://github.com/u8views/go-u8views/assets/92454023/1e8bdd3c-a1a2-470a-ae75-427f9c6a40dc)

Could it be fixed (or at least given choice to configure somehow), if possible?

Thank you!

**Comment by YaroslavPodorvanov** [comment]
@helitopia , all requests go through the [GitHub Camo](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls) proxy, so I am unable to track uniqueness

```text
If you upload an image or video to GitHub, the URL of the image or video will be modified so your information is not trackable.
```
