### ISSUE TITLE
Is there a way to set the total count in prior while using u8views tool 

### ISSUE THREAD

**Issue by ajithvcoder** [u8views/go-u8views#38]
For example i was using another tool(https://komarev.com)  for few years and my profile view count is 4200+ , i want to remove it and add u8views tool . 
in this tool there is a way (https://github.com/antonkomarev/github-profile-views-counter?tab=readme-ov-file#base-number) 

Is there any way to do it in u8views ?

one thing that differentiates u8views from others is you have a history record of profile views with respect to dates i want to have it

**Comment by lulunac27a** [comment]
Currently not supported yet.

**Comment by ajithvcoder** [comment]
thanks for the info
